name = "LinearCombinationPreconditioners"
uuid = "a2295072-fef1-44aa-a59b-d288b38b6fdf"
authors = ["Mark Transtrum <mktranstrum@byu.edu>"]
version = "0.1.1"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SuiteSparse = "4607b0f0-06f3-5cda-b6b1-a6196a1729e9"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
